### ISSUE TITLE
NameError: uninitialized constant 

### ISSUE THREAD

**Issue by jovercao** [anteo/redmine_custom_workflows#122]
Using redmine 4.0.2 with custom-workflows v1.0，I catch a error when restart redmine:

```bash
Resolving dependencies...
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
The Gemfile's dependencies are satisfied
rake aborted!

NameError: uninitialized constant RedmineCustomWorkflows::Patches::GroupPatch::CustomWorkflow
/usr/src/redmine/plugins/redmine_custom_workflows-1.0.0/lib/redmine_custom_workflows/patches/group_patch.rb:47:in `included'
/usr/src/redmine/plugins/redmine_custom_workflows-1.0.0/lib/redmine_custom_workflows/patches/group_patch.rb:82:in `include'
/usr/src/redmine/plugins/redmine_custom_workflows-1.0.0/lib/redmine_custom_workflows/patches/group_patch.rb:82:in `<top (required)>'
/usr/src/redmine/plugins/redmine_custom_workflows-1.0.0/lib/redmine_custom_workflows.rb:30:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/src/redmine/plugins/redmine_custom_workflows-1.0.0/init.rb:38:in `<top (required)>'
/usr/src/redmine/lib/redmine/plugin.rb:173:in `block in load'
/usr/src/redmine/lib/redmine/plugin.rb:164:in `each'
/usr/src/redmine/lib/redmine/plugin.rb:164:in `load'
/usr/src/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/usr/src/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:337:in `require'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
W, [2019-04-03T02:05:46.841909 #22]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2019-04-03T02:05:46.844738 #22]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
```

**Comment by picman** [comment]
Please update your master branch and try it again.

**Comment by picman** [comment]
A few more tuning concerning the error.
