### ISSUE TITLE
Error install on Redmine 4.1.0

### ISSUE THREAD

**Issue by koren85** [anteo/redmine_custom_workflows#149]
Hi! I get error after install plugin on Redmine 4.1.0:

```
NoMethodError: undefined method `assets' for #<Rails::Engine::Configuration:0x000000000474bc20>
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:20:in `<class:Engine>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:9:in `<module:RedmineExtensions>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:8:in `<top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `require_relative'
/home/redmine/data/tmp/bundle/ruby/2.4.0/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `<top (required)>'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:74:in `require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:69:in `each'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:69:in `block in require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:58:in `each'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler/runtime.rb:58:in `require'
/var/lib/gems/2.4.0/gems/bundler-2.1.3/lib/bundler.rb:174:in `require'
/home/redmine/redmine/config/application.rb:18:in `<top (required)>'
/home/redmine/redmine/Rakefile:5:in `require'
/home/redmine/redmine/Rakefile:5:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

**Comment by koren85** [comment]
My Redmine:
```
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.4.9-p362 (2019-10-02) [x86_64-linux-gnu]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.9.3
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.24.1
  Filesystem                     
Redmine plugins:
```

**Comment by picman** [comment]
Fixed. As a workaround upgrade the gem redmine_extensions 0.3.9.
e.g.
```
gem update redmine_extensions
```

**Comment by simpleuser99** [comment]
I have the same issue. My Redmine:
```
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            1.8.3.1
  Filesystem
Redmine plugins:
  no plugin installed
```

My issue:

```
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Engine::Configuration:0x00000000039cd0a8>
/usr/local/rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/railtie/configuration.rb:97:in `method_missing'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:20:in `<class:Engine>'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:9:in `<module:RedmineExtensions>'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions/engine.rb:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `require_relative'
/usr/local/rvm/gems/ruby-2.6.3/gems/redmine_extensions-0.2.16/lib/redmine_extensions.rb:1:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `require'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
/var/www/html/my-redmine.ru/config/application.rb:18:in `<top (required)>'
/var/www/html/my-redmine.ru/Rakefile:5:in `require'
/var/www/html/my-redmine.ru/Rakefile:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.6.3/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/var/www/html/my-redmine.ru/bin/rake:4:in `<main>'
```


My redmine_extensions is:
```
/usr/local/rvm/rubies/ruby-2.6.3/bin/gem list | grep -i ext
redmine_extensions (0.3.9, 0.2.16)
```

**Comment by simpleuser99** [comment]
If I uninstall redmine_extensions 0.3.9, I have the next result:

```
/var/www/html/my-redmine.ru/bin/rake --trace redmine:plugins:migrate
Could not find redmine_extensions-0.2.16 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by aceccarelli** [comment]
Show!!! thank you @picman 
It worked!
