### ISSUE TITLE
Crash when delete project

### ISSUE THREAD

**Issue by ludovicandrieux** [anteo/redmine_custom_workflows#167]
Hi,

When i try to delete a project from administration panel, i get an HTTP 500.
I have no workflow active during test.

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL 11.7
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.5.3
  redmine_checklists             3.1.16
  redmine_custom_workflows       1.0.2
  redmine_lightbox2              0.5.1
```

In the log, i can find this :
```ruby
Started DELETE "/projects/aaa" for 2a01:e35:242f:4c90:9c93:df60:11aa:72e3 at 2020-05-11 11:08:00 +0200
Processing by ProjectsController#destroy as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"QtYaxIlKkzDccBjsYeibW6FMsTSmElzYRcWxsJSnwJT1Z38M+23nMp+45iSs8/iDvCYdg1L9kmNXBlrBf4hpYQ==", "confirm"=>"1", "commit"=>"Supprimer", "id"=>"aaa"}
  Current user: xxx@xxx.com (id=1)
Completed 500 Internal Server Error in 48ms (ActiveRecord: 20.5ms)

ActiveRecord::StatementInvalid (PG::UndefinedTable: ERREUR:  la relation « easy_settings » n'existe pas
LINE 8:                WHERE a.attrelid = '"easy_settings"'::regclas...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"easy_settings"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
):

app/controllers/projects_controller.rb:264:in `destroy'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

Thanks for your help.

**Comment by picman** [comment]
Take a loook here: https://github.com/danmunn/redmine_dmsf/issues/1092

**Comment by ludovicandrieux** [comment]
Thanks, it's solved my problem.

My proposal ?
* Short term : Update the documentation in README.md
* Long term : Put the code from db:migrate in db:migrate:plugins  more usual

Waht do you think ?

**Comment by picman** [comment]
From the README
```
Installation

From a ZIP file:

    Download the latest version of the plugin
    Unzip to /plugins

From a GIT repository:

    Clone repository with git clone https://github.com/anteo/redmine_custom_workflows.git plugins/redmine_custom_workflows command

After download:

    Run rake redmine:plugins:migrate
    Restart Redmine
```
What is missing?

**Comment by ludovicandrieux** [comment]
You need to write 
Run rake redmine:plugins:migrate and Run rake redmine:migrate

**Comment by ludovicandrieux** [comment]
You should update this page too : https://www.redmine.org/plugins/custom-workflows-plug-in

**Comment by picman** [comment]
You're right. Done.
