### ISSUE TITLE
MySQL error on install

### ISSUE THREAD

**Issue by usualstuff** [anteo/redmine_custom_workflows#19]
Hello.

I've been unable to install plugin due to error:

```
== 20150526132244 CreateExampleWorkflow: migrating ============================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Field 'after_save' doesn't have a default value: INSERT INTO `custom_workflows` (`name`, `author`, `description`, `before_save`, `created_at`, `updated_at`, `position`) VALUES ('Duration/Done Ratio/Status correlation', 'anton.argirov@gmail.com', 'Set up a correlation between the start date, due date, done ratio and status of issues.\n\n* If done ratio is changed to 100% and status is \"In Process\", status changes to \"Resolved\"\n* If status is \"New\", \"Resolved\" or \"Feedback\" and done ratio is changed to value less than 100%, status changes to \"In process\"\n* If status is changed to \"In process\" and start date is not set, then it sets to current date\n* If status is changed to \"Resolved\" and end date is not set, then it set to due date\n\nTo use this script properly, turn off \"Use current date as start date for new issues\" option in the settings as this script already do it own way.\n', 'if @issue.done_ratio_changed?\n  if @issue.done_ratio==100 && @issue.status_id==2\n    @issue.status_id=3\n  elsif [1,3,4].include?(@issue.status_id) && @issue.done_ratio<100\n    @issue.status_id=2\n  end\nend\n\nif @issue.status_id_changed?\n  if @issue.status_id==2\n    @issue.start_date ||= Time.now\n  end\n  if @issue.status_id==3\n    @issue.done_ratio = 100\n    @issue.start_date ||= @issue.created_on\n    @issue.due_date ||= Time.now\n  end\nend\n', '2015-07-07 09:42:45', '2015-07-07 09:42:45', 2)/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters
(truncated)
```

This reproducing on clean install.
I've tried to fix this by disabling MySQL option "STRICT_TRANS_TABLES" but it didn't work. 

Redmine version: 3.0.3
Ruby version: ruby 2.0.0p598
Gems:
mysql2 (0.3.18)
activerecord (4.2.1)
MySQL version: Percona 5.6.25-73.0

thanks,
Alex

**Comment by anteo** [comment]
Did you installed plugin from scratch or run migrate on old version?
What is your current sql_mode variable value (SHOW VARIABLES LIKE 'sql_mode')?
Make dump of custom_workflows table structure (SHOW CREATE TABLE custom_workflows)

I've tested plugin on Mysql 5.6.x with default sql mode (STRICT_TRANS_TABLES,STRICT_ALL_TABLES) and it was ok.

**Comment by usualstuff** [comment]
I've actually trying to migrate to new version of redmine and plugin.
Maybe old table actually causing problems but when I dropping it I get something like "'redmine.custom_workflows' doesn't exist" on plugin migration. 

```
mysql> SHOW VARIABLES LIKE 'sql_mode';
+---------------+--------------------------------------------+
| Variable_name | Value                                      |
+---------------+--------------------------------------------+
| sql_mode      | NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+--------------------------------------------+
```
```
mysql> SHOW CREATE TABLE custom_workflows;
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table            | Create Table                                                                                                                                                                                                                                                                                                                                                                           |
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| custom_workflows | CREATE TABLE `custom_workflows` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `before_save` text NOT NULL,
  `after_save` text NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `position` int(11) NOT NULL DEFAULT '1',
  `is_for_all` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 |
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by anteo** [comment]
Execute following sql and run ```rake redmine:plugins:migrate````` again

    ALTER TABLE `custom_workflows` CHANGE `before_save` `before_save` TEXT NULL, CHANGE `after_save` `after_save` TEXT NULL;

If won't help,

    DROP TABLE `custom_workflows`;
    DELETE FROM schema_migrations WHERE version LIKE '%-redmine_custom_workflows';

**Comment by anteo** [comment]
And if you overwrote plugin files (without deleting plugin folder and copying new files), some old files could stay in migrations folder, that prevent you to migrate.

**Comment by usualstuff** [comment]
Thank you so much! 
The "alter table" method worked and everything seems fine.

Closing issue, thank you for your time.
