### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by koren85** [anteo/redmine_custom_workflows#194]
Hello! Thanks for plugin!

I get Erorr 500 when I use this code in before_save:

```
if self.tracker_id==6
  if Group.find(318).users.include? self.assigned_to
    #nothing
else
   errors.add '', "Error!."
end
end
raise WorkflowError, 'Errors found. Please contact the Admin for assistance as required.' unless errors.blank?

```
The error occurs when I want to handle the error:
```
errors.add '', "Error!."
raise WorkflowError, 'Errors found. Please contact the Admin for assistance as required.' unless errors.blank?
```
in production.log I found this:

```
== User workflow error: Errors found. Please contact the Admin for assistance as required.
= Abort running before_save custom workflows for Issue (#) "Task #: hyhgh"
  Rendering issues/new.html.erb within layouts/base
  Rendered plugins/additionals/app/views/issues/_new_ticket_message.html.slim (0.9ms)
  Rendered issues/new.html.erb within layouts/base (11.4ms)
Completed 500 Internal Server Error in 168ms (ActiveRecord: 47.9ms)

ActionView::Template::Error (undefined method `humanize' for nil:NilClass):
    4:
    5: <%= labelled_form_for @issue, :url => _project_issues_path(@project),
    6:                              :html => {:id => 'issue-form', :multipart => true} do |f| %>
    7:   <%= error_messages_for 'issue' %>
    8:   <%= hidden_field_tag 'copy_from', params[:copy_from] if params[:copy_from] %>
    9:   <div class="box tabular">
   10:     <div id="all_attributes">

config/initializers/10-patches.rb:18:in `human_attribute_name'
app/helpers/application_helper.rb:1255:in `block in error_messages_for'
app/helpers/application_helper.rb:1255:in `map'
app/helpers/application_helper.rb:1255:in `error_messages_for'
app/views/issues/new.html.erb:7:in `block in _d2e27c2cbad00dadaaba40c6a2c03cc2'
app/helpers/application_helper.rb:1242:in `labelled_form_for'
app/views/issues/new.html.erb:5:in `_d2e27c2cbad00dadaaba40c6a2c03cc2'
app/controllers/issues_controller.rb:147:in `block (2 levels) in create'
app/controllers/issues_controller.rb:142:in `create'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
Creating scope :system. Overwriting existing method Enumeration.system.
Starting That Issue Reply Button plugin for Redmine
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :visible. Overwriting existing method Principal.visible.

```
Is the error related to the presence of other plugins?
How can I fix this if I can?

Glad for any help)

Thanks!

**Comment by AirTibu** [comment]
Hi,

Use this code:
```

    if self.tracker_id==6
        if Group.find(318).users.include? self.assigned_to
            #nothing
        else
            raise WorkflowError, 'Errors found. Please contact the Admin for assistance as required.'
            return true
        end
    end

```
I hope its help!

**Comment by koren85** [comment]
Hi,

Yes, it helped me. Thank you so much!
