### ISSUE TITLE
Getting NameError: uninitialized constant RedmineExtensions Error in installation

### ISSUE THREAD

**Issue by gaurav-cointab** [anteo/redmine_custom_workflows#218]
I executed this command after bundle install
  bundle exec rake db:migrate RAILS_ENV=production

This was the output. Can you help what should I do?
  NameError: uninitialized constant RedmineExtensions
  /usr/local/www/redmine/plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/attachment_patch.rb:64:in `<top (required)>'
  /usr/local/www/redmine/plugins/redmine_custom_workflows/lib/redmine_custom_workflows.rb:30:in `<top (required)>'
  /usr/local/www/redmine/plugins/redmine_custom_workflows/after_init.rb:23:in `<top (required)>'
  /usr/local/www/redmine/plugins/redmine_custom_workflows/init.rb:43:in `require_relative'
  /usr/local/www/redmine/plugins/redmine_custom_workflows/init.rb:43:in `<top (required)>'
  /usr/local/www/redmine/lib/redmine/plugin.rb:187:in `block in load'
  /usr/local/www/redmine/lib/redmine/plugin.rb:178:in `each'
  /usr/local/www/redmine/lib/redmine/plugin.rb:178:in `load'
  /usr/local/www/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
  /usr/local/www/redmine/config/environment.rb:16:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

Redmine 4.2
Ruby 2.7.3
Rails 5.2.5

**Comment by gaurav-cointab** [comment]
This was fixed by installing the "redmine_extensions" gem, and later had to add one more gem "acts_as_list" in the Gemfile.local in the redmine root directory.
