### ISSUE TITLE
production.log

### ISSUE THREAD

**Issue by ashrafalzyoud** [anteo/redmine_custom_workflows#295]
how i know which custom workflow id have error in production.log

**Comment by ashrafalzyoud** [comment]
```
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:165:in `process'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionview-6.1.6.1/lib/action_view/rendering.rb:39:in `process'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:190:in `dispatch'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:254:in `dispatch'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in `each'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in `serve'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:37:in `call_app'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:28:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/content_length.rb:17:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/engine.rb:539:in `call'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
== Custom workflow exception: Couldn't find Group with 'id'=82
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/core.rb:346:in `find'
 (eval):3:in `block in run'
 (eval):2:in `each'
 (eval):2:in `run'
 /var/www/5.0.2/plugins/redmine_custom_workflows/app/models/custom_workflow.rb:97:in `instance_eval'
 /var/www/5.0.2/plugins/redmine_custom_workflows/app/models/custom_workflow.rb:97:in `run'
 /var/www/5.0.2/plugins/redmine_custom_workflows/app/models/custom_workflow.rb:84:in `block in run_custom_workflows'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/relation/delegation.rb:88:in `each'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/relation/delegation.rb:88:in `each'
 /var/www/5.0.2/plugins/redmine_custom_workflows/app/models/custom_workflow.rb:83:in `run_custom_workflows'
 /var/www/5.0.2/plugins/redmine_custom_workflows/lib/redmine_custom_workflows/patches/models/issue_patch.rb:87:in `after_save_custom_workflows'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:516:in `block in invoke_after'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:516:in `each'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:516:in `invoke_after'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:131:in `block in run_callbacks'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/callbacks.rb:457:in `create_or_update'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/timestamp.rb:126:in `create_or_update'
 /var/www/5.0.2/app/models/issue.rb:228:in `create_or_update'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/persistence.rb:474:in `save'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/validations.rb:47:in `save'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:298:in `block in save'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:298:in `save'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/suppressor.rb:44:in `save'
 /var/www/5.0.2/app/controllers/issues_controller.rb:661:in `block in save_issue_with_child_records'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:209:in `transaction'
 /var/www/5.0.2/app/controllers/issues_controller.rb:642:in `save_issue_with_child_records'
 /var/www/5.0.2/app/controllers/issues_controller.rb:197:in `update'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:228:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 /var/www/5.0.2/lib/redmine/sudo_mode.rb:61:in `sudo_mode'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-6.1.6.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:165:in `process'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionview-6.1.6.1/lib/action_view/rendering.rb:39:in `process'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:190:in `dispatch'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:254:in `dispatch'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in `each'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in `serve'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:842:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/http/content_security_policy.rb:19:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/cookies.rb:689:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:37:in `call_app'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:28:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/content_length.rb:17:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
 /home/redmine/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-6.1.6.1/lib/rails/engine.rb:539:in `call'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
 /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by ashrafalzyoud** [comment]
I have 35 custom work flow script

I wanna know which one have error in production.log

Any code?!
@picman

**Comment by picman** [comment]
I've extended the log message with custom workflow's name and ID:
```
ERROR -- : == Custom workflow c1, #31 exception: Couldn't find Group with 'id'=1016
```
In the present version you should see a similar message with the custom workflow's name prior the error message
```
INFO -- : == Running before_save custom workflow "My custom workflow"
```

**Comment by ashrafalzyoud** [comment]
this code cause the problem

```
unless self.parent.nil?
  self.parent.watcher_user_ids.each do |w_user|
      Watcher.create(:watchable_type=> 'Issue',:watchable_id=> self.id,:user_id=> w_user) unless Group.find(w_user).nil?
  end
end
```

**Comment by ashrafalzyoud** [comment]
@picman

**Comment by picman** [comment]
`Group.find(w_user)` -> `User.find(w_user)` ?

**Comment by ashrafalzyoud** [comment]
```
unless self.parent.nil?
  self.parent.watcher_user_ids.each do |w_user|
      Watcher.create(:watchable_type=> 'Issue',:watchable_id=> self.id,:user_id=> w_user) unless User.find(w_user).nil?
  end
end
u mean this correct
```

**Comment by picman** [comment]
Yes.

**Comment by ashrafalzyoud** [comment]
thx for u @picman
