### ISSUE TITLE
Redmine 3.2.1 - Internal Server Error on new Issue with MS SQL

### ISSUE THREAD

**Issue by andreav** [anteo/redmine_custom_workflows#63]
Hi,
I'm trying this plugin on redmine 3.2.1 and I get Internal Server Error when saving a new issue.
Following the stack trace: from logs:

```
Started POST "/redmine/projects/sottoprogetto_001-test/issues" for 127.0.0.1 at 2016-06-28 08:39:33 +0200
Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"1eycUaR01eXUsH9IzUCUYxoQUO1UdprdFa5tS0qpO/IGylaijr0SHJaBJALRDtag7G+NOVKF3mPKF1fZZnC9xA==", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "tracker_id"=>"9", "subject"=>"AAA", "description"=>"AAA", "status_id"=>"7", "priority_id"=>"10", "assigned_to_id"=>"", "parent_issue_id"=>"", "start_date"=>"2016-06-28", "custom_field_values"=>{"6"=>"2016-06-03", "20"=>"", "21"=>"", "48"=>["XXX", ""], "4"=>"0", "5"=>"", "9"=>"", "25"=>"", "26"=>"", "27"=>"", "29"=>"", "33"=>"", "34"=>"", "35"=>"", "55"=>"", "37"=>"", "49"=>"", "44"=>"", "47"=>"", "42"=>"", "50"=>"Atteso", "51"=>"", "52"=>"", "45"=>"0", "46"=>"0"}}, "was_default_status"=>"7", "commit"=>"Crea", "project_id"=>"sottoprogetto_001-test"}
  Current user: admin (id=1)
= Running shared code for Issue (#) "Delivery #: AAA"
= Finished running shared code for Issue (#) "Delivery #: AAA"
Completed 500 Internal Server Error in 2621ms (ActiveRecord: 99.8ms)

ActiveRecord::StatementInvalid (TinyTds::Error: An expression of non-boolean type specified in a context where a condition is expected, near 'OR'.: EXEC sp_executesql N'SELECT COUNT(*) FROM [custom_workflows] WHERE [custom_workflows].[active] = @0 AND [custom_workflows].[observable] = @1 AND (is_for_all OR EXISTS (SELECT * FROM custom_workflows_projects WHERE project_id=16 AND custom_workflow_id=id))', N'@0 bit, @1 nvarchar(255)', @0 = 1, @1 = 'issue'):
  plugins/redmine_custom_workflows/app/models/custom_workflow.rb:73:in `run_custom_workflows'
  plugins/redmine_custom_workflows/lib/redmine_custom_workflows/issue_patch.rb:47:in `before_save_custom_workflows'
  app/models/issue.rb:182:in `create_or_update'
  app/controllers/issues_controller.rb:141:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

Any idea?
Thank you.

**Comment by andreav** [comment]
As a note, I have no workflows configured.

**Comment by jdkemme** [comment]
What database type are you using?  It appears the following query in the plugin is not compatible with MS Sql

```
app/models/custom_workflow.rb 
34	  scope :active, lambda { where(:active => true) }
35	  scope :for_project, (lambda do |project|
36	    where("is_for_all OR EXISTS (SELECT * FROM #{projects_join_table} WHERE project_id=? AND custom_workflow_id=id)", project.id)
```
is_for_all is being tested as boolean, which doesn't work in mssql.  This line could be modified to `where("is_for_all=1 OR...`

There may be other incompatible queries, but this is the one in your error.

**Comment by andreav** [comment]
Hi,
I'm on:
OS: Windows Server 2012
Database: SQLServer 11.0.2100

and inside database.yml i have:

production:
  adapter: sqlserver
  database: REDMINE
  username: xx
  password: yy
  dataserver: SRVWEB02
  timeout: 200000

**Comment by andreav** [comment]
I just tried your patch and I can confirm it works great!!

Thank you!

**Comment by picman** [comment]
Fixed.
